### PR TITLE
fixup! Add Dialyzer plugin

### PR DESCRIPTION
**Pull request by yannayl**
add dialyzer_warnings_filter_function option. Note, such functions can
be defined only in rebar.config.script file.

### CODE REVIEW

**Comment by tuncer** [comment]
Thanks for the patch. Do you mind for rebar#460 to land and submit the patch at rebar/rebar?

**Comment by yannayl** [comment]
Sure, when will that happen?

**Comment by tuncer** [comment]
@ferd, @fishcakez, when do you think we can land rebar#460?

**Comment by fishcakez** [comment]
@tuncer, sorry, I have been meaning to check the file names in warnings for modules in deps in build-plt/check-plt.

**Comment by tuncer** [comment]
Closing as a result of the discussion in rebar#460.

**Pull request closed without merging**
